# country_data.py

# 1) Master list of countries
COUNTRIES = [
    "Saudi Arabia", "Australia", "Armenia", "Brazil", "Canada", "China",
    "Czech Republic", "Denmark", "Netherlands", "United Kingdom", "Estonia",
    "Philippines", "France", "Germany", "Greece", "Israel", "Hungary",
    "India", "Indonesia", "Italy", "Japan", "South Korea", "Mexico",
    "Norway", "Iran", "Poland", "Portugal", "Romania", "Russia", "Serbia",
    "Spain", "Sweden", "Thailand", "Turkey", "Ukraine", "USA", "Pakistan"
]

# 2) Cities by country
CITIES_BY_COUNTRY = {
    "Saudi Arabia": ["Riyadh"],
    "Australia": ["Sydney", "Melbourne"],
    "Armenia": ["Yerevan"],
    "Brazil": ["Sao Paulo", "Rio de Janeiro"],
    "Canada": ["Toronto", "Montreal"],
    "China": ["Beijing", "Shanghai"],
    "Czech Republic": ["Prague"],
    "Denmark": ["Copenhagen"],
    "Netherlands": ["Amsterdam", "Rotterdam"],
    "United Kingdom": ["London", "Manchester", "Birmingham"],
    "Estonia": ["Tallinn"],
    "Philippines": ["Manila"],
    "France": ["Paris", "Lyon", "Marseille"],
    "Germany": ["Berlin", "Munich", "Frankfurt"],
    "Greece": ["Athens"],
    "Israel": ["Tel Aviv"],
    "Hungary": ["Budapest"],
    "India": ["Mumbai", "Delhi"],
    "Indonesia": ["Jakarta"],
    "Italy": ["Rome", "Milan"],
    "Japan": ["Tokyo", "Osaka", "Kyoto"],
    "South Korea": ["Seoul", "Busan"],
    "Mexico": ["Mexico City"],
    "Norway": ["Oslo"],
    "Iran": ["Tehran"],
    "Poland": ["Warsaw", "Krakow"],
    "Portugal": ["Lisbon", "Porto"],
    "Romania": ["Bucharest"],
    "Russia": ["Moscow", "Saint Petersburg"],
    "Serbia": ["Belgrade"],
    "Spain": ["Madrid", "Barcelona"],
    "Sweden": ["Stockholm"],
    "Thailand": ["Bangkok"],
    "Turkey": ["Istanbul", "Ankara", "Izmir"],
    "Ukraine": ["Kyiv", "Lviv"],
    "USA": ["New York", "Los Angeles", "Chicago"],
    "Pakistan": ["Islamabad"]
}

# 3) Official/Widely Spoken Languages by Country
LANGUAGES_BY_COUNTRY = {
    "Saudi Arabia": ["Arabic"],
    "Australia": ["English"],
    "Armenia": ["Armenian"],
    "Brazil": ["Portuguese"],
    "Canada": ["English", "French"],
    "China": ["Mandarin"],
    "Czech Republic": ["Czech"],
    "Denmark": ["Danish"],
    "Netherlands": ["Dutch"],
    "United Kingdom": ["English"],
    "Estonia": ["Estonian"],
    "Philippines": ["Filipino", "English"],
    "France": ["French"],
    "Germany": ["German"],
    "Greece": ["Greek"],
    "Israel": ["Hebrew"],
    "Hungary": ["Hungarian"],
    "India": ["Hindi", "English"],
    "Indonesia": ["Indonesian"],
    "Italy": ["Italian"],
    "Japan": ["Japanese"],
    "South Korea": ["Korean"],
    "Mexico": ["Spanish"],
    "Norway": ["Norwegian"],
    "Iran": ["Persian"],
    "Poland": ["Polish"],
    "Portugal": ["Portuguese"],
    "Romania": ["Romanian"],
    "Russia": ["Russian"],
    "Serbia": ["Serbian"],
    "Spain": ["Spanish"],
    "Sweden": ["Swedish"],
    "Thailand": ["Thai"],
    "Turkey": ["Turkish"],
    "Ukraine": ["Ukrainian"],
    "USA": ["English"],
    "Pakistan": ["Urdu", "English"]
}
